### ISSUE TITLE
How can I assign specific encoding for sourceDirectory?

### ISSUE THREAD

**Issue by SeungminHeo** [HenrikBengtsson/R.utils#103]
Hi.

I'am making shiny apps with your R.utils packages, especially with sourceDirectory.

This is what a convenient method, but I have a problem with it.

I'm using language Korean, this language is very sensitive to encodings. 

I need to specifying encoding for a folder, but I can't find way to do it.

Is there any way to do it?

**Comment by HenrikBengtsson** [comment]
I think you can pass the `encoding` argument all the way down to `base::source()`, which used for each of the files source:d. So try with, e.g.
```r
sourceDirectory(path, encoding = "UTF-8")
```

**Comment by HenrikBengtsson** [comment]
Did my suggestion work? Can I close this?

**Comment by SeungminHeo** [comment]
> Did my suggestion work? Can I close this?

Sorry that I'm late. 

I used your suggestion and solved problem :)
