### ISSUE TITLE
getAbsolutePath: incorrect result when the path goes to the parent of tilde on Windows

### ISSUE THREAD

**Issue by daattali** [HenrikBengtsson/R.utils#111]
Perhaps this happens on unix too, I haven't tested.

```
> R.utils::getAbsolutePath("~", expandTilde = TRUE)
[1] "C:/Users/Dean/Documents"
> R.utils::getAbsolutePath("~/../Documents", expandTilde = TRUE)
[1] "./Documents"
```

My actual usecase that found this bug was when I was trying to go into my downloads folder (`~/../Downloads`) and it returned a path that was unusable

**Comment by HenrikBengtsson** [comment]
Thxs, I can confirm that this happens on Linux to (and on R devel):
```r
> R.utils::getAbsolutePath("~", expandTilde = TRUE)
[1] "/home/alice"
> R.utils::getAbsolutePath("~/../Documents", expandTilde = TRUE)
[1] "./Documents"
```

**Comment by HenrikBengtsson** [comment]
Fixed for the next release.

**Comment by HenrikBengtsson** [comment]
R.utils 2.10.1 fixing this problem is now on CRAN

**Comment by daattali** [comment]
Confirmed fixed
