### ISSUE TITLE
View() confuses list elements commonly named

### ISSUE THREAD

**Issue by earnaud** [HenrikBengtsson/R.utils#113]
Here is a little issue I am experiencing with the `View()` function: I parse severe .xsd files to work on their content. When I check the contents are correctly structured, I see that elements located on the same level that are named the same way are shown with `View()` as having the same content. (see screenshot)

**Reprex**
I am working with the .xsd files for the Ecological Metadata Language. You can find them from [here](https://eml.ecoinformatics.org/schema/). Here is my chunk of code to read and view them:
```
library(XML)
library(dplyr)

xsd.files <- dir("/path/to/xsd/files/", pattern="eml", full.names = TRUE)
xsd <- lapply(xsd.files, function(file){
  xmlParse(file) %>% xmlRoot %>% xmlToList
})
names(xsd) <- basename(xsd.files)

View(xsd)
```
Once in the viewer pane, navigate to **xsd / eml-access.xsd / complexType (1st) / choice / choice**. Here are two `element` tags, and their `.attr` tags both contain `'allow' 'AccesssRule'` (see screenshot).

Thanks you by advance for replying to this issue, and thanks you again for this great package !

![image](https://user-images.githubusercontent.com/43677175/80109756-2cab0380-857e-11ea-9baf-1aec6278e664.png)

**Comment by HenrikBengtsson** [comment]
Hi there. Great report. Unfortunately, that is a for a function in the 'utils' package.  This is about R.utils, cf. Issue #114

**Comment by earnaud** [comment]
Oh, I'm sorry :/

**Comment by HenrikBengtsson** [comment]
No worries
