### ISSUE TITLE
Uncaught error when trying to get a path that goes up too many directories above the root

### ISSUE THREAD

**Issue by daattali** [HenrikBengtsson/R.utils#119]
Version 2.10.1 Windows 10 

Assuming I'm in my home directory:

```
> setwd("~")
> R.utils::getAbsolutePath(".")
[1] "C:/Users/D/Documents"
> R.utils::getAbsolutePath("./../../../..")
[1] ""
> R.utils::getAbsolutePath("./../../../../..")
Error in if (components[pos] == ".." && components[pos - 1L] != "..") { : 
  missing value where TRUE/FALSE needed
```

I suppose this isn't too bad, because I literally went to a directory that doesn't exist (although a nicer error message could be more user friendly).

But I also get that error message when doing something less crazy:

```
> R.utils::getAbsolutePath("~", expandTilde = TRUE)
[1] "C:/Users/D/Documents"
> R.utils::getAbsolutePath("~/../..", expandTilde = TRUE)
[1] "C:/Users"
> R.utils::getAbsolutePath("~/../..")
Error in if (components[pos] == ".." && components[pos - 1L] != "..") { : 
  missing value where TRUE/FALSE needed
```

If I forget to use tilde expansion, even though I'm still in a directory that exists, I get an unhelpful error message because as far as the tilde-unaware path is concerned, it's too high up. Perhaps you'd consider this a feature vs bug.

**Comment by HenrikBengtsson** [comment]
Thanks for reporting; I can reproduce this with:

```r
> R.utils::filePath("/tmp/../../..", removeUps = TRUE)
Error in if (components[pos] == ".." && components[pos - 1L] != "..") { : 
  missing value where TRUE/FALSE needed

> traceback()
3: removeUpsFromPathname(pathname)
2: filePath.default("/tmp/../../..", removeUps = TRUE)
1: R.utils::filePath("/tmp/../../..", removeUps = TRUE)
```

**Comment by HenrikBengtsson** [comment]
Actually, after thinking a bit more about it (and admitting I'm a bit rusty on the original design here), I don't think there's be an error at all.

The purpose of `filePath()` is to work like `base::file.path()`, but with some extra bells and whistles, e.g. to prune away `.` and `..` components, _if possible_.  When not possible, it should return what's possible, e.g.

```r
> R.utils::filePath('C:/..')
[1] "C:/.."
> R.utils::filePath('C:/../..')
[1] "C:/../.."
```

Now, this behavior is immediately inherited by `getAbsolutePath()`, so we should get:

```r
> R.utils::getAbsolutePath('C:/..')
[1] "C:/.."

> R.utils::getAbsolutePath('C:/../..')
[1] "C:/../.."

> R.utils::getAbsolutePath('~/../..')
[1] "~/../.."

> R.utils::getAbsolutePath('~/../..', expandTilde = TRUE)
[1] "C:/Users"
```

or, in your case,

```r
> R.utils::getAbsolutePath("C:/Users/D/Documents/./../../../..")
[1] "C:/.."
```

That's the best simplify the specified path.

It's up to other functions to validate the resulting path.  Having said that, according to the POSIX standards, paths like `/..` is the same as `/`.  Interestingly, on MS Windows, at least on MS Windows 10, it looks like the parent directory of `C:\` is also `C:\`, e.g. `dir C:\..\..` gives the same as `dir C:\`.  The `base::normalizePath()` function handles these cases.

**Comment by daattali** [comment]
Whether or not the behaviour is technically "correct" is not something I have an opinion on. 

But in either case, I will argue that the error message is bad. 

The following is truly meaningless for a user:

```
> R.utils::getAbsolutePath("~/../..")
Error in if (components[pos] == ".." && components[pos - 1L] != "..") { : 
  missing value where TRUE/FALSE needed
```

**Comment by HenrikBengtsson** [comment]
> But in either case, I will argue that the error message is bad.
> 
> The following is truly meaningless for a user:
> 
> ```
> > R.utils::getAbsolutePath("~/../..")
> Error in if (components[pos] == ".." && components[pos - 1L] != "..") { : 
>   missing value where TRUE/FALSE needed
> ```

Sorry for not being clear, in the next release (currently in the develop branch), you'll get:

```r
R.utils::getAbsolutePath("~/../..")
[1] "~/../.."
```

So, not an obscure, side-effect error.

**Comment by daattali** [comment]
Ah, yes that'll do :)
