### ISSUE TITLE
withTimeout does not return NULL

### ISSUE THREAD

**Issue by aboghossian** [HenrikBengtsson/R.utils#132]
When using the `"warning"` option, `withTimeout` returns the warning message string rather than `NULL` (as stated in the documentation).

For example:
```
> x <- R.utils::withTimeout(Sys.sleep(2), timeout = 1, onTimeout = "warning", substitute = F)
Warning message:
In value[[3L]](cond) : reached elapsed time limit [cpu=1s, elapsed=1s]
> x
[1] "reached elapsed time limit [cpu=1s, elapsed=1s]"
```

**Comment by HenrikBengtsson** [comment]
Thank you for reporting. Fixed in the next release, cf. commit a63f1bf5.
