### ISSUE TITLE
Unable to install package: HTTP status was '403 Forbidden' 

### ISSUE THREAD

**Issue by diaz292** [HenrikBengtsson/R.utils#138]
`install.packages("R.utils")` fails on Windows work computer due to access restrictions:

```
Warning in install.packages :
 cannot open URL 'https://cran.rstudio.com...' : HTTP status was '403 Forbidden'
```

Tried changing repository to 'https://henrikbengtsson.r-universe.dev' and got the same result. Installation from Github is blocked so unable to test.

Going to package source file (R.utils_2.12.0.tar.gz) on the CRAN site, I get a "Access to the Website is restricted...this web page contains content that is not in compliance with the End User Acceptable Use Standard" message from INFOSEC (courtesy of Zscalar). 

Haven't gotten such issues with any other packages,  so not sure what is causing it for {R.utils}.

**Comment by HenrikBengtsson** [comment]
This is the first and only time I've got a report on this for one of my package. This definitely sounds like an issue with some too-eager malware scanner you've got on your end.  They might scan for some file checksum and it could be that **R.utils** has the same checksum as some know malware. It's definitely a false positive and not correct.  Please report upstream to INFOSEC/Zscalar.
