### ISSUE TITLE
Problem installing R.utils package

### ISSUE THREAD

**Issue by DrJohan** [HenrikBengtsson/R.utils#144]
Hi

I've been trying to install this package but have been unsuccessful both using the CRAN and Github version. 
Below are the errors I encountered when I'm trying to install this package. 

"Error in setGenericS3.default(name, export = exportGeneric, envir = envir,  : 
  (converted from warning) Renamed the preexisting function warnings to warnings.default, which was defined in environment R.utils.
Error: unable to load R code in package 'R.utils'
Execution halted

Any idea how I can resolve this issue?

Thanks

**Comment by HenrikBengtsson** [comment]
You have `options(warn = 2)` set. Try in a fresh R session. If you have set it in your ~/.Rprofile file, remove it from there.

**Comment by DrJohan** [comment]
Thank you so much @HenrikBengtsson . Now it works like a charm.
