### ISSUE TITLE
littler & commandArgs

### ISSUE THREAD

**Issue by daroczig** [HenrikBengtsson/R.utils#27]
It seems that @eddelbuettel's `littler` is not compatible with `commandArgs` (neither in `base` or `R.utils`) as it already captures the command line arguments: https://github.com/eddelbuettel/littler/blob/c9cbae87fb29c88af4812f16585b5b07eced8dbb/README#L209

But it would be great to parse those arguments as a named list just like `commandArgs` does via `asValue = TRUE`. Any plans to add support for this? Maybe looking for the `argv` variable in the global namespace (where `littler` assigns the command line arguments by default)?

**Comment by eddelbuettel** [comment]
Yup. Lemme know if I can help. The getopt author accomodated me a few years ago.  Littler also works really well with docopt.  Just don't do it by hand, or if you, also support `argv`.

**Comment by daroczig** [comment]
Thanks a lot, @eddelbuettel, `docopt` indeed works fine with `r`. I have no idea how I missed this.
@HenrikBengtsson, please feel free to close this ticket if you do not need this suggested feature.
Thank you, both!

**Comment by HenrikBengtsson** [comment]
@daroczig, the manual solution to this is to do something like:
```r
> r -e "str(R.utils::commandArgs(asValue=TRUE, .args=argv))" a=1 b=TRUE c=3.14
List of 3
 $ a: chr "1"
 $ b: chr "TRUE"
 $ c: chr "3.14"
```

**Comment by HenrikBengtsson** [comment]
I've added built-in support for [littler](https://cran.r-project.org/package=littler), e.g.
```r
$ r -e "str(R.utils::commandArgs(asValue=TRUE, excludeReserved=TRUE))" a=1 b=TRUE c=3.14
List of 4
 $  : chr "littler"
 $ a: chr "1"
 $ b: chr "TRUE"
 $ c: chr "3.14"
```
and
```
$ r -e "str(R.utils::commandArgs(asValue=TRUE, excludeReserved=TRUE, adhoc=TRUE))" a=1 b=TRUE c=3.14
List of 4
 $  : chr "littler"
 $ a: int 1
 $ b: logi TRUE
 $ c: num 3.14
```

Until on CRAN, to install this develop version, use:
```r
source("http://callr.org/install#HenrikBengtsson/R.utils@develop")
```

**Comment by daroczig** [comment]
Thanks a lot!

**Comment by HenrikBengtsson** [comment]
FYI, R.utils 2.2.0 supporting littler is on CRAN.

**Comment by eddelbuettel** [comment]
:+1:
