### ISSUE TITLE
evalWithTimeout

### ISSUE THREAD

**Issue by arnaud-m** [HenrikBengtsson/R.utils#34]
Dear Henrik,

The function evalWithTimeout of R.utils does not work as expected because you are searching for an english exception message
```R
 pattern <- gettext("reached elapsed time limit")
```
 whereas these can be translated (in French).
```R
> res <- evalWithTimeout({
+   foo();
+ }, timeout=1.08, onTimeout="warning");
[1] "Tic"
[1] 1
...
[1] 11
Error in Sys.sleep(0.1) : la limite de temps est atteinte


```

Thank you for your time.
Arnaud

Here is my configuration : 

```
Package: R.utils
 Version: 2.1.0
 Maintainer: Henrik Bengtsson <henrikb@braju.com>
 Built: R 3.2.2; ; 2015-11-17 20:24:28 UTC; unix

R Version:
 platform = x86_64-redhat-linux-gnu
 arch = x86_64
 os = linux-gnu
 system = x86_64, linux-gnu
 status = 
 major = 3
 minor = 2.2
 year = 2015
 month = 08
 day = 14
 svn rev = 69053
 language = R
 version.string = R version 3.2.2 (2015-08-14)
 nickname = Fire Safety

Locale:
 LC_CTYPE=fr_FR.utf8;LC_NUMERIC=C;LC_TIME=fr_FR.utf8;LC_COLLATE=fr_FR.utf8;LC_MONETARY=fr_FR.utf8;LC_MESSAGES=fr_FR.utf8;LC_PAPER=fr_FR.utf8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=fr_FR.utf8;LC_IDENTIFICATION=C

Search Path:
 .GlobalEnv, package:R.utils, package:R.oo, package:R.methodsS3,
 package:stats, package:graphics, package:grDevices, package:utils,
 package:datasets, package:methods, Autoloads, package:base
```

**Comment by HenrikBengtsson** [comment]
Thanks for the report.  I've updated code to:
```r
pattern <- gettext("reached elapsed time limit", domain="R")
```
such that `pattern` becomes the proper string for whatever language is in use, e.g. `"la limite de temps est atteinte"` with `LANGUAGE=fr`.  With the default `domain=NULL`, it incorrectly searched the R.utils package for translations.

Until I submit to CRAN, you can install the develop version from GitHub by:
```r
source("http://callr.org/install#HenrikBengtsson/R.utils@develop")
```

PS. The "new" name is `withTimeout()` - old/alias `evalWithTimeout()` will become deprecated.

**Comment by arnaud-m** [comment]
Thank you very much, it was a very responsive bug fix  :satisfied:

**Comment by HenrikBengtsson** [comment]
@arnaud-m FYI, R.utils 2.2.0 is now on CRAN.
