### ISSUE TITLE
Error in document of captureOutput

### ISSUE THREAD

**Issue by mvkorpel** [HenrikBengtsson/R.utils#4]
In the function `captureOutput`, the handling of the argument `collapse` doesn't seem to match its description in the (embedded) `.Rd` document. How the argument actually works does make sense, the corresponding documentation does not.

Another detail, probably not deserving a separate report, is a small typo in the same document: "js evaluated" should read "is evaluated".

**Comment by HenrikBengtsson** [comment]
Thanks  - fixed in the 'develop' branch, cf. commit b7c3b2.  FYI, you can install this branch by:
```r
source('http://callr.org/install#HenrikBengtsson/R.utils@develop')
```
