### ISSUE TITLE
chooseCRANmirror {utils} local mirror

### ISSUE THREAD

**Issue by naresh050414** [HenrikBengtsson/R.utils#46]
For a corporate environment, I want our R users to use our local repository only. I have made corresponding required changes to Rprofile.site, .Rprofile, and repositories files as suggested by other posts and it works fine for changing the repository option only to the local one. However, a user is still able to select a CRAN mirror by selecting "Set CRAN Mirror" from the menu or by running "chooseCRANmirror()" command and when she does either of these, it will add standard CRAN repository as a repository option again. This behavior is in line with what is mentioned in help documentaiton 
"A list of mirrors is stored in file ‘R_HOME/doc/CRAN_mirrors.csv’, but first an on-line list of current mirrors is consulted, and the file copy used only if the on-line list is inaccessible" but is it possible to change the default functionality of referencing "online mirrors first" and directly go to local mirrrs.csv file?

**Comment by HenrikBengtsson** [comment]
This is the R.utils package. You're asking about the utils package of R, which is different. Please ask on the r-help mailing list.

**Comment by naresh050414** [comment]
Sorry for the confusion and thanks!
