### ISSUE TITLE
View mode - filter 

### ISSUE THREAD

**Issue by ronencozen** [HenrikBengtsson/R.utils#50]
Can't paste a value to the filter text box, using paste from by right-clicking the mouse and selecting paste from the context menu.

How to reproduce:
1. view any data-frame
2. from the results copy any token 
3. select filter mode
4. right click the mouse and select paste -- nothing happen, you need to switch to the keyboard CTRL+V in order to paste.

**Comment by HenrikBengtsson** [comment]
This issue tracker is for the `R.utils` package; it seems you're asking for something in the `utils` package that is part of core R.  For the latter, I suggest the r-help mailing list.
