### ISSUE TITLE
read.table converts column 1 into row names or spoils column names

### ISSUE THREAD

**Issue by alexbpotapov** [HenrikBengtsson/R.utils#59]
Hi, i used read.table for a table where col. 1 consisted of variable names. Without specifying row.names parameter, the 1-st column was always converted to row names. When row.names=NULL, col. 1 appears in the data frame but with a new name "row.names", and all column names were shifted to the left, i.e. name of the col. 1 appears as a name for column 2 etc.

Thanks,
Alex

   df = read.table(tabname, header = TRUE, colClasses = "character", row.names=NULL,
         sep=",", quote = "\"", stringsAsFactors = FALSE, as.is=TRUE, fill=TRUE)
   print(df)
                     row.names  VARNAME    count distinct    NULLs  Repeated
1                    RECORD_ID     48829263 48829263        0        0         
2                PR_NAME     48829263        1        0 48829262         
3                  Z_NUMBER     48829263        5        0 48829258

**Comment by HenrikBengtsson** [comment]
This is the [R.utils](https://cran.r-project.org/web/packages/R.utils/) package, which is different from the utils package that `read.table()` is part of.  The utils package comes with R, whereas R.utils is a contributed package.  Sorry for the confusion.

You might wanna reach out to the official r-help mailing list about your question.
