### ISSUE TITLE
reassignInPackage documentation of keepOld should specify name of attribute

### ISSUE THREAD

**Issue by PeterVermont** [HenrikBengtsson/R.utils#69]
I can see from the source code that it is 'oldValue'. Adding that to the documentation would be helpful. An example showing how to call the oldValue from within the newValue would be nice as in my case I simply wish to add code around the existing code.

**Comment by HenrikBengtsson** [comment]
Help now mentions the name of the attribute.

Skipping adding extra example, especially since `reassignInPackage()` is a "use-at-your-own-risk-and-only-if-you-know-what-you're-doing" function.
