### ISSUE TITLE
withTimeout(): add more examples where timeout is not supported

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/R.utils#74]
The `help("withTimeout")` has a [section on 'Non-supported cases'](https://github.com/HenrikBengtsson/R.utils/blob/master/R/withTimeout.R#L42-L62).  This section could be improved by adding more cases, e.g. `system()` calls.  It may also be valuable to add explicit code example that doesn't support timeout, e.g. from https://github.com/HenrikBengtsson/future/issues/169#issuecomment-338348689:
```r
withTimeout({ z <- rnorm(1000000000) }, timeout = 1) # requires about ~8GB free memory
withTimeout({ system("sleep 10") }, timeout = 1)
```

PS. Note that in R (>= 3.5.0), `system()` and `system2()` gained argument `timeout`.

**Comment by rcannood** [comment]
Fyi, the following code solved the problem, but will apparently only work on Linux and macOS platforms and not on Windows:
``` R
eval_fork <- function(..., timeout = 60) {
  myfork <- parallel::mcparallel({
  eval(...)
  }, silent = FALSE)

  # wait max n seconds for a result.
  myresult <- parallel::mccollect(myfork, wait = FALSE, timeout = timeout)
  # kill fork after collect has returned
  tools::pskill(myfork$pid, tools::SIGKILL)
  tools::pskill(-1 * myfork$pid, tools::SIGKILL)

  # clean up:
  parallel::mccollect(myfork, wait = FALSE)
  # timeout?
  if (is.null(myresult)) 
  stop("reached elapsed time limit")

  # move this to distinguish between timeout and NULL returns
  myresult <- myresult[[1]]

  # send the buffered response
  return(myresult)
}
```

Source: http://blog.revolutionanalytics.com/2014/10/r-in-production-controlling-runtime.html

**Comment by wlandau-lilly** [comment]
What is going on under the hood with `setTimeLimit()` and `withTimeout()`? I am using `withTimeout()` for [drake](https://github.com/wlandau-lilly/drake/blob/master/R/run.R#L41), and the timeouts are prone to failure, depending on the execution environment and the command used. Are global variables or options set somewhere?

**Comment by HenrikBengtsson** [comment]
`R.utils::withTimeout(expr)` is basically a neat wrapper that sets `base::setTimeLimit()` and evaluates the expression `expr` in the calling environment, so nothing funny done there.  I'd expect `base::setTimeLimit()` is also playing fair.

**Comment by wlandau-lilly** [comment]
That makes sense. At this point, I'm really after the internals and side effects of `base::setTimeLimit()`, so I submitted an [SO post](https://stackoverflow.com/questions/46931416/settimelimit-internal-behavior) just now.
