### ISSUE TITLE
PECULIARITY: withTimeout() and Sys.sleep()

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/R.utils#77]
The following times out (on Linux) only _after_ `Sys.sleep()` completes, but not during;
```r
> R.utils::withTimeout({
  message("ping")
  Sys.sleep(3)
  message("pong")
}, timeout = 0.5)
ping
[2017-10-22 17:31:25] TimeoutException: reached elapsed time limit [cpu=0.5s, elapsed=0.5s]
> 
```

In other words, it correctly produces a timeout error, but it does not pre-terminate the `Sys.sleep()` per se.

This should probably be reported/brought up on the R-devel mailing list; note that `base::setTimeLimit()` does all the timeout work internally.  I have a vague memory that someone already done this in the past.  It should also be checked what the behavior is on Windows, because there it might work differently (which is what I used when I wrote [the help page, which also needs to be updated, cf. ["during Sys.sleep"](https://github.com/HenrikBengtsson/R.utils/blob/master/R/withTimeout.R#L48)).

**Comment by HenrikBengtsson** [comment]
Hmm... it's actually `help("setTimeLimit", package = "base")` that claims that `Sys.sleep()` can be timed out:
> *Details*
> ...
> Time limits are checked whenever a user interrupt could occur. This will happen frequently in R code and during Sys.sleep, but only at points in compiled C and Fortran code identified by the code author.

**Comment by HenrikBengtsson** [comment]
Reproducing this problem in a fresh R session using just `base::setTimeLimit()`:
```r
$ R --vanilla
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS
[...]
> setTimeLimit(cpu = 1.0, elapsed = 1.0, transient=FALSE)
> t0 <- Sys.time(); try(Sys.sleep(3)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(3) : reached elapsed time limit
Time difference of 3.243988 secs

> t0 <- Sys.time(); try(Sys.sleep(2)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(2) : reached elapsed time limit
Time difference of 2.00346 secs
```
However, on Windows it works as expected / documented:
```r
R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
[...]
> setTimeLimit(cpu = 1.0, elapsed = 1.0, transient=FALSE)
> t0 <- Sys.time(); try(Sys.sleep(3)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(3) : reached elapsed time limit
Time difference of 1.031049 secs
```
Either way, this is definitely not a problem with `R.utils::withTimeout()`.

**Comment by HenrikBengtsson** [comment]
Ilari S confirms the same problem on macOS: ["3s, with R 3.3.3 on Yosemite 10.10.5."](https://twitter.com/ilarischeinin/status/926581167633174528).

**Comment by HenrikBengtsson** [comment]
Moved to https://github.com/HenrikBengtsson/Wishlist-for-R/issues/47

**Comment by mllg** [comment]
3 seconds.

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

**Comment by alexrecuenco** [comment]
I got one second in MacOS. 
```
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)
> setTimeLimit(cpu = 1.0, elapsed = 1.0, transient=FALSE)
> t0 <- Sys.time(); try(Sys.sleep(3)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(3) : reached elapsed time limit
Time difference of 1.00736 secs
Error: reached elapsed time limit
```

**Comment by HenrikBengtsson** [comment]
The reason for this has been identified; see https://github.com/HenrikBengtsson/Wishlist-for-R/issues/47.

**Comment by ilarischeinin** [comment]
Just to confirm that the `quartz(); dev.off()` trick that was mentioned on the [R-devel thread from 2013](https://stat.ethz.ch/pipermail/r-devel/2013-May/066650.html) still applies on macOS 10.13 High Sierra and R 3.4.2:

```r
$ R --vanilla
R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)
[...]
> setTimeLimit(cpu = 1.0, elapsed = 1.0, transient=FALSE)
> t0 <- Sys.time(); try(Sys.sleep(3)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(3) : reached elapsed time limit
Time difference of 3.007089 secs
> quartz(); dev.off()
null device 
          1 
> t0 <- Sys.time(); try(Sys.sleep(3)) ; dt <- Sys.time() - t0; print(dt)
Error in Sys.sleep(3) : reached elapsed time limit
Time difference of 1.080138 secs
```
