### ISSUE TITLE
intToBin and negative integers

### ISSUE THREAD

**Issue by schoonees** [HenrikBengtsson/R.utils#78]
Hi

This might be a bit pedantic, but intToBin() does not seem to do anything sensible for negative integers. For example, 

`> R.utils::intToBin(-5:5)`
` [1] "011" "100" "101" "110" "111" "000" "001" "010" "011" "100" "101"`

Or

`> R.utils::intToBin(c(-100, -10, -5))`
`[1] "0" "0" "1"`

Most likely you did not intend these functions to be used in this way. Maybe you can document this behaviour, or let negative integers result in an error? I am not an expert on binary numbers (and did not bother reading up about representing negative binary numbers), so I could be wrong, but at the very least the results aren't consistent.

I stumbled on this while creating programming exercises for a course I am teaching. I was looking for a function to compare my results against, and found intToBin(). Hence this is not really high priority, but I thought I would mention it.

Keep up the good work!

Pieter

**Comment by HenrikBengtsson** [comment]
Thxs; this certainly needs some attention / fixes.  Add it to the todo list for next release.

**Comment by HenrikBengtsson** [comment]
This has been fixed in the develop version.  For example,
```r
> R.utils::intToBin(-5:5)
 [1] "1111111111111111111111111111011" "1111111111111111111111111111100" "1111111111111111111111111111101"
 [4] "1111111111111111111111111111110" "1111111111111111111111111111111" "0000000000000000000000000000000"
 [7] "0000000000000000000000000000001" "0000000000000000000000000000010" "0000000000000000000000000000011"
[10] "0000000000000000000000000000100" "0000000000000000000000000000101"
```
and
```r
> R.utils::intToBin(c(-100, -10, -5))
[1] "1111111111111111111111110011100" "1111111111111111111111111110110" "1111111111111111111111111111011"
```
Note that the padding of zeros and ones, is driven by the maximum needed representation, which is why:
```r
> R.utils::intToBin(c(-1, 5))[2]
"0000000000000000000000000000101"
```
gives a different output than:
```
> R.utils::intToBin(5)
[1] "101"
```
The padding is now documented in the help.
