### ISSUE TITLE
ls.str and lsf.str ignore/treat differently argument name

### ISSUE THREAD

**Issue by EmilBode** [HenrikBengtsson/R.utils#91]
From the documentation of ls.str and lsf.str it was my understanding that the 'name' argument had the same role as in ls(), but their behaviour differs, it looks like the default of pos (-1, or current) overrules the name.
Example:

```
>ls(name='package:utils')
(...) (214 items from utils, as expected)
>lsf.str(pos='package:utils')
(...) (212 lines with utils functions, as expected)
>lsf.str(name='package:utils')
(...)(list of functions in current environment)
>lsf.str()
(...)(list of functions in current environment)
```
While I expected the 3rd command to give the same output as the 2nd, instead of identical to the last one.
Is this a bug, or did I misunderstand the docs? And if it's the 2nd case, in what way should I use the name argument?

**Comment by HenrikBengtsson** [comment]
Wrong package, this is the R.utils pkg.
