### ISSUE TITLE
Registered S3 method overwritten by R.oo

### ISSUE THREAD

**Issue by GeraldCNelson** [HenrikBengtsson/R.utils#95]
Since R version 3.6 was released I have been getting messages from a variety of packages like the following
```
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
```
It seems the class "throw.default" of your package is conflicting with the same class of package {R.methodsS3}. Would there be any chance either of you could rename your class to use your package name as a prefix? It probably makes sense to do this renaming in the package with the fewest reverse dependencies, to minimise breakages.

**Comment by HenrikBengtsson** [comment]
Hi. Yes, I'm aware of this warning in R (>= 3.6.0).  This is actually independent of the R.utils package. It comes from R.oo, e.g.
```r
> loadNamespace("R.oo")
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
<environment: namespace:R.oo>
> 
```
This design is on purpose and well tested and used for many years.  That "note" should be of no concern per se.  It is just that it's quite annoying to get every time R.oo is loaded.

I'll see what I can do, e.g. I've created https://github.com/HenrikBengtsson/R.methodsS3/issues/15, which is related to this.  Renaming the function/method will not be part of the solution.

**Comment by GeraldCNelson** [comment]
It is especially annoying when you don't even know what R.oo is! I think I have figured out that R.oo is a dependency of one of the dependencies of a package I use. I hadn't installed it until these messages started appearing, and in some cases causing problems. 

Using suppressPackageStartupMessages(library(RSelenium)) stops the message from appearing but I worry that it will also suppress some messages I'd like to see.

**Comment by Steviey** [comment]
+1

**Comment by HenrikBengtsson** [comment]
For updates on this issue, please see https://github.com/HenrikBengtsson/R.methodsS3/issues/15.  That is what is going to solve it.  As you can see, I have started the long and slow process of getting this resolved.  Lots of it requires downstream packages to be updated.  AFAIK, there is no quick fix for this, so please be patient.

**Comment by GeraldCNelson** [comment]
Appreciated!

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by jangorecki** [comment]
I recall reporting that somewhere already but cannot find, and this hits me again so putting another example here
```r
library(data.table)
#data.table 1.12.3 IN DEVELOPMENT built 2019-09-03 09:07:48 UTC; jan using 2 threads (see ?getDTthreads).  Latest news: r-datatable.com
d = fread("http://stat-computing.org/dataexpo/2009/1987.csv.bz2")
#trying URL 'http://stat-computing.org/dataexpo/2009/1987.csv.bz2'
#Content type 'application/x-bzip2' length 12652442 bytes (12.1 MB)
#==================================================
#downloaded 12.1 MB
#
#Registered S3 method overwritten by 'R.oo':
#  method        from       
#  throw.default R.methodsS3
```
User might be confused by an extra, unrelated stderr output

**Comment by HenrikBengtsson** [comment]
@jangorecki, please comment https://github.com/HenrikBengtsson/R.utils/issues/95#issuecomment-498449972 above.

**Comment by HenrikBengtsson** [comment]
Please try with:
```r
remotes::install_github("HenrikBengtsson/R.oo@feature/export-throw")
```

**Comment by HenrikBengtsson** [comment]
Fixed in [R.oo 1.23.0](https://cran.r-project.org/web/packages/R.oo) which is now on CRAN, e.g.
```r
> loadNamespace("R.oo")
<environment: namespace:R.oo>
>
```
or
```r
> library(data.table)
data.table 1.12.6 using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
> d <- fread("http://stat-computing.org/dataexpo/2009/1987.csv.bz2")
trying URL 'http://stat-computing.org/dataexpo/2009/1987.csv.bz2'
Content type 'application/x-bzip2' length 12652442 bytes (12.1 MB)
==================================================
downloaded 12.1 MB
>
```
